FROM python:3.10-alpine

WORKDIR /usr/src/app

ADD requeriments.txt .

RUN pip install --trusted-host pypi.python.org -r requeriments.txt

CMD [ "uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]